### ISSUE TITLE
Morning report

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#24]
After your latest update kraken was fixed.Seems to work OK now.I will post if i ecnounter a problem,

Unfortunately poloniex private api now doesn't work.

This is the error i get when i try to access private api.It worked in the last version of ccxt.
```
Traceback (most recent call last):
  File "C:\oop\novi ws\Crypto\TransactionFees.py", line 8, in get_transaction_fee
    response = self.request(command, type='private', method='POST')
  File "C:\oop\novi ws\Crypto\ccxt.py", line 8600, in request
    'Sign': self.hmac (self.encode (body), self.secret, hashlib.sha512),
  File "C:\oop\novi ws\Crypto\ccxt.py", line 373, in hmac
    h = hmac.new (secret, request, algorithm)
  File "C:\Program Files (x86)\Python36-32\lib\hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "C:\Program Files (x86)\Python36-32\lib\hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
```

Furthermore when i try to access GDAX and its private api this is what I get:
```
Traceback (most recent call last):
  File "C:\oop\novi ws\Crypto\TransactionFees.py", line 50, in get_transaction_fee
    response = self.request(command, type='private', method='GET')
  File "C:\oop\novi ws\Crypto\ccxt.py", line 6373, in request
    'CB-ACCESS-PASSPHRASE': self.password,
AttributeError: 'gdax' object has no attribute 'password'
```

So the problem here seems to be in the request of gdax
``` 
else:
            nonce = str (self.nonce ())
            if query:
                body = self.json (query)
            what = nonce + method + request + (body or '')
            secret = base64.b64decode (self.secret)
            signature = self.hmac (self.encode (what), secret, hashlib.sha256, 'binary')
            headers = {
                'CB-ACCESS-KEY': self.apiKey,
                'CB-ACCESS-SIGN': base64.b64encode (signature),
                'CB-ACCESS-TIMESTAMP': nonce,
                'CB-ACCESS-PASSPHRASE': self.password,
            }
        return self.fetch (url, method, headers, body)
```

there is no password.Tried changing it to secret but that's not it.

And I tried a few other and the problem from poloniex is repeated.

I m sorry for bothering you too much I will be more than happy to do the test once you find the problem.
Let me know if you need anything else.

**Comment by kroitor** [comment]
Hi! I made a quickfix for the GDAX part, update and check if it's ok with your password and please report here on the results. For GDAX you should set 3 pieces of info:
apiKey
secret
password
There was one little bug but it seems like it should work now.

As for poloniex – I'm fixing it too very soon, keep in touch. You're not bothering me at all, all your feedback is welcome, man)

**Comment by marinsokol5** [comment]
Now the problem might be from my side.
It says 
`gdax GET https://api.gdax.com/users/self/trailing-volume 
400 Bad Request b'{"message":"Invalid Passphrase"}'`

Though in your private/get urls there is one just like it.

**Comment by marinsokol5** [comment]
Poloniex now works.
Livecoin however does the same thing 

`File "C:\Program Files (x86)\Python36-32\lib\site-packages\ccxt\__init__.py", line 7725, in request
    signature = self.hmac (body, self.secret, hashlib.sha256)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ccxt\__init__.py", line 375, in hmac
    h = hmac.new (secret, request, algorithm)
  File "C:\Program Files (x86)\Python36-32\lib\hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "C:\Program Files (x86)\Python36-32\lib\hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
`

**Comment by kroitor** [comment]
Ok, I uploaded a fix for Poloniex and updated the version. Download it and try again, please.

First, try this by running python and:
```Python
import ccxt
poloniex = ccxt.poloniex ({
	'apiKey': '6ORNNIXJ-EGXMM5BT-EEGJ5NRV-H78QHS3D',
	'secret': '065aad42b2656f374974f4e42558b2d5071f31187aa973210186932acb2f2f3d86e2c481ddf5436e56596a50d4833f00e002d467d1d0597022a9a81ff4e66506',
})
print (poloniex.fetch_balance ())
```

It should work if you launch python in console and paste it there. Substitute for your keys when everything is ok. 

As for GDAX, you should do try running similar python code in console, paste:

```Python
import ccxt
gdax = ccxt.gdax ({
        'verbose': True,
	'apiKey': '92560ffae9b8a01d012726c698bcb2f1',
	'secret': '9aHjPmW+EtRRKN/OiZGjXh8OxyThnDL4mMDre4Ghvn8wjMniAr5jdEZJLN/knW6FHeQyiz3dPIL5ytnF0Y6Xwg==',
	'password': '6kszf4aci8r',
})
gdax.urls['api'] = 'https://api-public.sandbox.gdax.com'
print (gdax.fetch_balance ())
```

Does this example work?

**Comment by marinsokol5** [comment]
The code you pasted for gdax works but no unofrtunately I still get the HTTP Error 400: Bad Request.
Can you check 
`command = 'users/self/trailing-volume'
response = market.request(command, type='private', method='GET')`
After initializing gdax.

**Comment by kroitor** [comment]
Can you please some code from your working context, meaning how you instantiate the gdax market and how you set up your keys (without actually showing your keys, of course, just cut them off)?

Also, can you run the following code and tell if it's working ? For me it returns an empty array (I have no trailing volume in their sandbox).
```
import ccxt
gdax = ccxt.gdax ({
	'apiKey': '92560ffae9b8a01d012726c698bcb2f1',
	'secret': '9aHjPmW+EtRRKN/OiZGjXh8OxyThnDL4mMDre4Ghvn8wjMniAr5jdEZJLN/knW6FHeQyiz3dPIL5ytnF0Y6Xwg==',
	'password': '6kszf4aci8r',
})

# this is a Sandbox URL, remove it when testing with your actual keys
gdax.urls['api'] = 'https://api-public.sandbox.gdax.com' 

print (gdax.private_get_users_self_trailing_volume ())
```

If it works, then delete the sandbox line and insert your credentials, then run the above code again and report, please.

**Comment by marinsokol5** [comment]
The code you sent works when its sandbox and your keys.It prints an empty field.
Upon putting my keys and removing the sandbox url it throws Bad request .

**Comment by kroitor** [comment]
Can you paste the output with 'verbose': True option? (remove your keys prior to pasting).

**Comment by marinsokol5** [comment]
`https://api.gdax.com/users/self/trailing-volume GET {'CB-ACCESS-KEY': '**********', 'CB-ACCESS-SIGN': b'rY8nUAnuc3MGzTDWkXUosFzE0uClmsrvbGenz6z8iQU=', 'CB-ACCESS-TIMESTAMP': '1500200210', 'CB-ACCESS-PASSPHRASE': '******', 'User-Agent': 'ccxt/0.1.0 (+https://github.com/kroitor/ccxt) Python/3.6.1'} None
gdax GET https://api.gdax.com/users/self/trailing-volume 400 Bad Request b'{"message":"Invalid Passphrase"}'`

**Comment by marinsokol5** [comment]
So now there is no error but it returnes `[ ]` for some reason.

Bitstamp still not working.

**Comment by kroitor** [comment]
Did you read [Overriding The Nonce](https://github.com/kroitor/ccxt/wiki/Manual#overriding-the-nonce) section in the Manual? It might be a nonce problem. Or you don't have traded trailing volume on that account. Or it may be a problem with GDAX API. Need to investigate further. One sec, I'll upload a fix for bitstamp.

**Comment by Tsuihao** [comment]
Hi everyone,

I have met the same problem as mentioned above from @marinsokol5 . 


`HTTPError: 400 Client Error: Bad Request for url: `https://api.gdax.com/accounts`

`During handling of the above exception, another exception occurred:
`

**and**

`ExchangeError: gdax {"message":"Invalid Passphrase"}`


ps: I did add 'password'

**Exchange**: Gdax

**Comment by kroitor** [comment]
@Tsuihao make sure you don't miss the last two symbols in the secret of GDAX (the base64 ending of `==` – that is also a part of the secret key). This is a common pitfall. Let me know, if this is not the case.

**Comment by Tsuihao** [comment]
@kroitor,
== is there, same as Kraken. And Kraken works for `fetch_blance()`.

**Comment by kroitor** [comment]
@Tsuihao does this work for you?

```Python
import ccxt

exchange = ccxt.gdax({
    'verbose': True,
	'apiKey': '45921fabb72e9e3e994abe94a27779e8',
	'secret': '8XvsofHVrNRQOEAXd2aQYZ/q/rmN933b23YDp6rk8NGoFdhzHMtu5kDHHa68fRauX9WWj2rAAJqoXVXmVBgCog==',
	'password': 'k1448bxrrqk',
})

# this is a Sandbox URL, remove it when testing with your actual keys
exchange.urls['api'] = exchange.urls['test']

print(exchange.fetch_balance())
```

**Comment by Tsuihao** [comment]
Hi @kroitor,

Yes this works for me.
However, when I switched with my own apiKey, secret, and password.

then `ExchangeError: gdax {"message":"Invalid Passphrase"}` showed

**Comment by kroitor** [comment]
@Tsuihao did you try recreating a new keyset (just to make sure you're not using wrong credentials with it)?

**Comment by Tsuihao** [comment]
@kroitor, It works!
I thought the '**password**' is my personal password, and it turned out to be the `Passphrase`.
I think the key name '**password**' is a bit misleading.
Thanks for the help :+1:
